name: Pipeline

on:
  push:
    branches:
      - 'main'

env:
  PIPELINE_USER_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}
  PIPELINE_USER_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SAM_TEMPLATE: template.yaml
  TESTING_STACK_NAME: scraper-dev
  TESTING_PIPELINE_EXECUTION_ROLE: arn:aws:iam::910774986370:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1DGU6ZKQINT59
  TESTING_CLOUDFORMATION_EXECUTION_ROLE: arn:aws:iam::910774986370:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-18TWCEXUHX2UR
  TESTING_ARTIFACTS_BUCKET: aws-sam-cli-managed-dev-pipeline-artifactsbucket-1rqm2l94k5k26
  # If there are functions with "Image" PackageType in your template,
  # uncomment the line below and add "--image-repository ${TESTING_IMAGE_REPOSITORY}" to
  # testing "sam package" and "sam deploy" commands.
  # TESTING_IMAGE_REPOSITORY = '0123456789.dkr.ecr.region.amazonaws.com/repository-name'
  TESTING_REGION: ap-southeast-1
  PROD_STACK_NAME: scraper-prod
  PROD_PIPELINE_EXECUTION_ROLE: arn:aws:iam::910774986370:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-1VP9J2MLTNO9Y
  PROD_CLOUDFORMATION_EXECUTION_ROLE: arn:aws:iam::910774986370:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-SZRB9O1R6RWC
  PROD_ARTIFACTS_BUCKET: aws-sam-cli-managed-prod-pipeline-artifactsbucket-sjxrkqilzuzn
  # If there are functions with "Image" PackageType in your template,
  # uncomment the line below and add "--image-repository ${PROD_IMAGE_REPOSITORY}" to
  # prod "sam package" and "sam deploy" commands.
  # PROD_IMAGE_REPOSITORY = '0123456789.dkr.ecr.region.amazonaws.com/repository-name'
  PROD_REGION: ap-southeast-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - run: sam build --use-container
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset